/*
Blast
*/
#define BLAST_MIN 12.00
#define BLAST_MAX 17.00
#define BLAST_EN_PERCH 5.00
#define BLAST_DAMAGE_PERCH 2.00
#define BLAST_COOLDOWN 5 SECONDS

/*
Erasercannon
*/
#define ERASERCANNON_MIN 17.00
#define ERASERCANNON_MAX 21.00
#define ERASERCANNON_EN_PERCH 5.00
#define ERASERCANNON_DAMAGE_PERCH 2.00
#define ERASERCANNON_COOLDOWN 10 SECONDS

/*
Omegacannon
*/
#define OMEGACANNON_MIN 25.00
#define OMEGACANNON_MAX 33.00
#define OMEGACANNON_EN_PERCH 7.00
#define OMEGACANNON_DAMAGE_PERCH 5.00
#define OMEGACANNON_COOLDOWN 25 SECONDS

/*
Vanishing Beam
*/
#define VANISHBEAM_MIN 15.00
#define VANISHBEAM_MAX 20.00
#define VANISHBEAM_EN_PERCH 5.00
#define VANISHBEAM_DAMAGE_PERCH 2.00
#define VANISHBEAM_COOLDOWN 30 SECONDS

/*
Gack
*/
#define GACK_MIN 18.00
#define GACK_MAX 23.00
#define GACK_EN_PERCH 5.00
#define GACK_DAMAGE_PERCH 2.00
#define GACK_COOLDOWN 30 SECONDS

/*
Eye Laser
*/
#define EYE_LASER_MIN 15.00
#define EYE_LASER_MAX 20.00
#define EYE_LASER_EN_PERCH 5.00
#define EYE_LASER_DAMAGE_PERCH 2.00
#define EYE_LASER_COOLDOWN 15 SECONDS

/*
Zap
*/
#define KAIKOSEN_MIN 15.00
#define KAIKOSEN_MAX 20.00
#define KAIKOSEN_EN_PERCH 8.00
#define KAIKOSEN_DAMAGE_PERCH 4.00
#define KAIKOSEN_COOLDOWN 30 SECONDS

/*
Kamehameha
*/
#define KAMEHAMEHA_MIN 19.00
#define KAMEHAMEHA_MAX 21.00
#define KAMEHAMEHA_EN_PERCH 3.00
#define KAMEHAMEHA_DAMAGE_PERCH 3.00
#define KAMEHAMEHA_COOLDOWN 10 SECONDS

/*
Retsuzan
*/
#define RETSUZAN_MIN 20.00
#define RETSUZAN_MAX 22.00
#define RETSUZAN_EN_PERCH 4.00
#define RETSUZAN_DAMAGE_PERCH 3.75
#define RETSUZAN_COOLDOWN 20 SECONDS

/*
Masenko
*/
#define MASENKO_MIN 19.00
#define MASENKO_MAX 22.00
#define MASENKO_EN_PERCH 4.00
#define MASENKO_DAMAGE_PERCH 2.00
#define MASENKO_COOLDOWN 10 SECONDS

/*
Renzoku
*/
#define RENZOKU_MIN 12.00
#define RENZOKU_MAX 14.00
#define RENZOKU_EN_PERCH 3.00
#define RENZOKU_DAMAGE_PERCH 2.00
#define RENZOKU_COOLDOWN 20 SECONDS

/*
Spirit Bomb
*/
#define SPIRITBOMB_MIN 30.00
#define SPIRITBOMB_MAX 35.00
#define SPIRITBOMB_EN_PERCH 4.00
#define SPIRITBOMB_DAMAGE_PERCH 8.00
#define SPIRITBOBM_COOLDOWN 30 SECONDS

/*
Destructodisc
*/
#define DESTRUCTODISC_MIN 17.00
#define DESTRUCTODISC_MAX 22.00
#define DESTRUCTODISC_EN_PERCH 3.00
#define DESTRUCTODISC_DAMAGE_PERCH 2.00
#define DESTRUCTODISC_COOLDOWN 20 SECONDS

/*
Tri-Beam
*/
#define TRIBEAM_MIN 25.00
#define TRIBEAM_MAX 30.00
#define TRIBEAM_EN_PERCH 3.00
#define TRIBEAM_DAMAGE_PERCH 3.50
#define TRIBEAM_COOLDOWN 20 SECONDS

/*
Death Beam
*/
#define DEATHBEAM_MIN 21.00
#define DEATHBEAM_MAX 22.00
#define DEATHBEAM_EN_PERCH 6.00
#define DEATHBEAM_DAMAGE_PERCH 7.00
#define DEATHBEAM_COOLDOWN 20 SECONDS

/*Kienzan
*/
#define KIENZAN_MIN 17.00
#define KIENZAN_MAX 22.00
#define KIENZAN_EN_PERCH 3.00
#define KIENZAN_DAMAGE_PERCH 2.00
#define KIENZAN_COOLDOWN 20 SECONDS

/*
Special Beam Cannon
*/
#define SPECIALBEAMCANNON_MIN 22.00
#define SPECIALBEAMCANNON_MAX 25.00
#define SPECIALBEAMCANNON_EN_PERCH 4.00
#define SPECIALBEAMCANNON_DAMAGE_PERCH 4.00
#define SPECIALBEAMCANNON_COOLDOWN 20 SECONDS

/*
Final Flash
*/
#define FINALFLASH_MIN 25.00
#define FINALFLASH_MAX 30.00
#define FINALFLASH_EN_PERCH 6.00
#define FINALFLASH_DAMAGE_PERCH 5.00
#define FINALFLASH_COOLDOWN 20 SECONDS

/*
Galick Gun
*/
#define GALICKGUN_MIN 21.00
#define GALICKGUN_MAX 25.00
#define GALICKGUN_EN_PERCH 3.00
#define GALICKGUN_DAMAGE_PERCH 3.00
#define GALICKGUN_COOLDOWN 10 SECONDS

/*
Kaio Heal
*/
#define KAIOHEAL_COOLDOWN 15 SECONDS

/*
Flame Slash
*/
#define FLAMESLASH_MIN 7.00
#define FLAMESLASH_MAX 11.00
#define FLAMESLASH_EN_PERCH 1.00
#define FLAMESLASH_DAMAGE_PERCH 6.00
#define FLAMESLASH_COOLDOWN 17 SECONDS


/*
Spirit Wave
*/
#define SPIRITWAVE_MIN 20.00
#define SPIRITWAVE_MAX 22.00
#define SPIRITWAVE_EN_PERCH 2.00
#define SPIRITWAVE_DAMAGE_PERCH 4.00
#define SPIRITWAVE_COOLDOWN 60 SECONDS

/*
Kizan
*/
#define KIZAN_MIN 15.00
#define KIZAN_MAX 20.00
#define KIZAN_EN_PERCH 6.00
#define KIZAN_DAMAGE_PERCH 4.00
#define KIZAN_COOLDOWN 10 SECONDS

/*
Gekiretsu
*/
#define GEKIRETSU_MIN 20.00
#define GEKIRETSU_MAX 25.00
#define GEKIRETSU_EN_PERCH 3.00
#define GEKIRETSU_DAMAGE_PERCH 3.00
#define GEKIRETSU_COOLDOWN 10 SECONDS

/*
Big Bang
*/
#define BIGBANG_MIN 25.00
#define BIGBANG_MAX 30.00
#define BIGBANG_EN_PERCH 5.00
#define BIGBANG_DAMAGE_PERCH 4.00
#define BIGBANG_COOLDOWN 15 SECONDS

/*
Essence Spear
*/
#define SOULSPEAR_MIN 17.00
#define SOULSPEAR_MAX 21.00
#define SOULSPEAR_EN_PERCH 3.00
#define SOULSPEAR_DAMAGE_PERCH 2.00
#define SOULSPEAR_COOLDOWN 20 SECONDS

/*
Divine Cannon
*/
#define DIVINECANNON_MIN 20.00
#define DIVINECANNON_MAX 25.00
#define DIVINECANNON_EN_PERCH 5.00
#define DIVINECANNON_DAMAGE_PERCH 2.50
#define DIVINECANNON_COOLDOWN 30 SECONDS


/*
Death Ball
*/
#define DEATHBALL_MIN 27.00
#define DEATHBALL_MAX 33.00
#define DEATHBALL_EN_PERCH 5.00
#define DEATHBALL_DAMAGE_PERCH 4.00
#define DEATHBALL_COOLDOWN 30 SECONDS

/*
Finish Buster
*/
#define BURNING_ATTACK_MIN 9.00
#define BURNING_ATTACK_MAX 11.00
#define BURNING_ATTACK_EN_PERCH 4.00
#define BURNING_ATTACK_DAMAGE_PERCH 4.50
#define BURNING_ATTACK_COOLDOWN 15 SECONDS

/*
Power Blitz
*/
#define POWERBLITZ_MIN 10.00
#define POWERBLITZ_MAX 12.00
#define POWERBLITZ_EN_PERCH 5.00
#define POWERBLITZ_DAMAGE_PERCH 6.50
#define POWERBLITZ_COOLDOWN 20 SECONDS
#define POWERBLITZ_MAX_BARRAGE_LOAD 3 


/*
Burning Attack
*/
#define FINISH_BUSTER_MIN 25.00
#define FINISH_BUSTER_MAX 30.00
#define FINISH_BUSTER_EN_PERCH 6.00
#define FINISH_BUSTER_DAMAGE_PERCH 5.00
#define FINISH_BUSTER_COOLDOWN 20 SECONDS

/*
Makosen
*/
#define MAKOSEN_MIN 20.00
#define MAKOSEN_MAX 25.00
#define MAKOSEN_EN_PERCH 3.00
#define MAKOSEN_DAMAGE_PERCH 3.00
#define MAKOSEN_COOLDOWN 10 SECONDS

/*
Super Kamehameha
*/
#define SUPER_KAMEHAMEHA_MIN 25.00
#define SUPER_KAMEHAMEHA_MAX 30.00
#define SUPER_KAMEHAMEHA_EN_PERCH 6.00
#define SUPER_KAMEHAMEHA_DAMAGE_PERCH 5.00
#define SUPER_KAMEHAMEHA_COOLDOWN 20 SECONDS

/*
Rocketpunch
*/
#define ROCKETPUNCH_MIN 10.00
#define ROCKETPUNCH_MAX 11.00
#define ROCKETPUNCH_EN_PERCH 4.00
#define ROCKETPUNCH_DAMAGE_PERCH 5.00
#define ROCKETPUNCH_COOLDOWN 20 SECONDS
